Add npm pre-push hook

diff --git a/pre-push/testing/npm b/pre-push/testing/npm
--- a/pre-push/testing/npm
+++ b/pre-push/testing/npm
@@ -1,11 +1,16 @@
 #!/bin/sh
 #
-# Runs `npm test` and doesn't push if a test fails.
+# Runs `npm run test-quickfail` and doesn't push if a test fails.
 
+set -e
+
+echo 'Testing...'
 
 # Add `test-quickfail` to `scripts` in `package.json` with appropriate option
 # from your testing framework.  E.g. for mocha:
 #
 #   `"test-quickfail": "mocha --bail"`
 #
-exec npm test-quickfail
+npm run test-quickfail
+
+echo 'Pushing...'
